Site:
  ProductName: "CompassCard"
  Environment: "PROD"
  SiteAlias: "compasscard.ca"

Settings:
    Browser: "Chrome"
    DeviceType: "Desktop"
    ShowOnMonitor: 2
    TestCategory: BVT
    RunInParallel: True
    PassedStepScreenshot: yes
    FailedStepScreenshot: yes

# Browsers
    # Chrome
    # Firefox

# Devices
    # Moto G4
    # Galaxy S5
    # Pixel 2
    # Pixel 2 XL
    # iPhone 5/SE
    # iPhone 6/7/8
    # iPhone 6/7/8 Plus
    # iPhone X
    # iPad
    # iPad Pro
    # Desktop

# RunInParallel
    # True
    # False

# PassedStepScreenshot
    # yes
    # no

# FaileddStepScreenshot
    # yes
    # no